openapi: 3.0.0
servers:
- url: https://app-dev-ws.notify-me.ch
  description: ''
- url: https://app-prod-ws.notify-me.ch
  description: ''
info:
  version: 1.1.0
  description: SwissCovid CN API
  title: SwissCovid CN API
paths:
  /v1/config:
    get:
      summary: getConfig
      description: Read latest configuration, depending on the version of the phone
        and the app.
      responses:
        '200':
          description: ConfigResponse with config parameters
          headers: {
            }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ch.ubique.swisscovid.cn.sdk.backend.model.config.ConfigResponse'
        '400':
          description: Invalid or improperly formatted user-agent or app-version
          headers: {
            }
      parameters:
      - name: User-Agent
        in: header
        description: App Identifier (PackageName/BundleIdentifier) + App-Version +
          OS (Android/iOS) + OS-Version
        example: ch.ubique.ios.notifyme;1.0.0;iOS;13.3
        required: true
        schema:
          type: string
  /v1/:
    get:
      summary: hello
      description: Hello return
      responses:
        '200':
          description: server live
          headers: {
            }
          content:
            application/json:
              schema:
                type: string
  /v1/traceKeys:
    get:
      summary: getTraceKeysJson
      description: getTraceKeysJson
      responses:
        '200':
          description: protobuf/json of all keys in that interval. response header
            _x-key-bundle-tag_ contains _lastKeyBundleTag_ for next request
          headers:
            x-key-bundle-tag:
              description: _lastKeyBundleTag_ to send with next request
              schema:
                type: string
          content:
            application/x-protobuf:
              schema:
                $ref: '#/components/schemas/ch.ubique.swisscovid.cn.sdk.backend.model.ProblematicEventWrapperOuterClass.ProblematicEventWrapper'
        '404':
          description: Invalid _lastKeyBundleTag_
          headers:
            x-key-bundle-tag:
              description: _lastKeyBundleTag_ to send with next request
              schema:
                type: string
      parameters:
      - name: lastKeyBundleTag
        in: query
        description: in millis since epoch. must be aligned to a full hour, and <
          now()
        example: ''
        required: false
        schema:
          type: integer
          format: long
    post:
      summary: uploadTraceKeys
      description: Endpoint used to upload trace keys to the backend
      responses:
        '200':
          description: The trace keys have been stored in the database
          headers: {
            }
          content:
            application/json:
              schema:
                type: string
        '403':
          description: Authentication failed
          headers: {
            }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ch.ubique.swisscovid.cn.sdk.backend.model.tracekey.v2.TraceKey'
        description: Trace key to upload as JSON
  /v1/register:
    post:
      summary: registerPush
      description: Push registration
      responses:
        '200':
          description: success
          headers: {
            }
        '400':
          description: Error
          headers: {
            }
      requestBody:
        required: true
        content:
          application/x-protobuf:
            schema:
              $ref: '#/components/schemas/ch.ubique.swisscovid.cn.sdk.backend.model.PushRegistrationOuterClass.PushRegistration'
        description: N/A
  /v3/:
    get:
      summary: hello
      description: Hello return
      responses:
        '200':
          description: server live
          headers: {
            }
          content:
            application/json:
              schema:
                type: string
  /v3/traceKeys:
    get:
      summary: getTraceKeysJson
      description: getTraceKeysJson
      responses:
        '200':
          description: protobuf/json of all keys in that interval. response header
            _x-key-bundle-tag_ contains _lastKeyBundleTag_ for next request
          headers:
            x-key-bundle-tag:
              description: _lastKeyBundleTag_ to send with next request
              schema:
                type: string
          content:
            application/x-protobuf:
              schema:
                $ref: '#/components/schemas/ch.ubique.swisscovid.cn.sdk.backend.model.v3.ProblematicEventWrapperOuterClass.ProblematicEventWrapper'
        '404':
          description: Invalid _lastKeyBundleTag_
          headers:
            x-key-bundle-tag:
              description: _lastKeyBundleTag_ to send with next request
              schema:
                type: string
      parameters:
      - name: lastKeyBundleTag
        in: query
        description: in millis since epoch. must be aligned to a full hour, and <
          now()
        example: ''
        required: false
        schema:
          type: integer
          format: long
    post:
      summary: uploadTraceKeys
      description: Endpoint used to upload trace keys to the backend
      responses:
        '200':
          description: The trace keys have been stored in the database
          headers: {
            }
          content:
            application/json:
              schema:
                type: string
        '403':
          description: Authentication failed
          headers: {
            }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ch.ubique.swisscovid.cn.sdk.backend.model.tracekey.v3.TraceKey'
        description: Trace key to upload as JSON
  /v3/register:
    post:
      summary: registerPush
      description: Push registration
      responses:
        '200':
          description: success
          headers: {
            }
        '400':
          description: Error
          headers: {
            }
      requestBody:
        required: true
        content:
          application/x-protobuf:
            schema:
              $ref: '#/components/schemas/ch.ubique.swisscovid.cn.sdk.backend.model.PushRegistrationOuterClass.PushRegistration'
        description: N/A
  /v3/userupload:
    post:
      summary: userUpload
      description: User upload of stored identities
      responses:
        '200':
          description: success
          headers: {
            }
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Upload Data
          headers: {
            }
        '403':
          description: Authentication failed
          headers: {
            }
      requestBody:
        required: true
        content:
          application/x-protobuf:
            schema:
              $ref: '#/components/schemas/ch.ubique.swisscovid.cn.sdk.backend.model.UserUploadPayloadOuterClass.UserUploadPayload'
        description: Identities to upload as protobuf
      parameters:
      - name: User-Agent
        in: header
        description: App Identifier (PackageName/BundleIdentifier) + App-Version +
          OS (Android/iOS) + OS-Version
        example: ch.ubique.android.dp3t;1.0;iOS;13.3
        required: true
        schema:
          type: string
components:
  schemas: {
    }
