openapi: 3.0.0
servers:
- url: https://app-dev-ws.notify-me.ch
  description: ''
- url: https://app-prod-ws.notify-me.ch
  description: ''
info:
  version: 1.0-develop
  description: NotifyMe API
  title: NotifyMe API
paths:
  /v1/:
    get:
      summary: hello
      description: Hello return
      responses:
        '200':
          description: server live
          content:
            application/json:
              schema:
                type: string
  /v1/traceKeys:
    get:
      summary: getTraceKeysJson
      description: getTraceKeysJson
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ch.ubique.notifyme.sdk.backend.model.TraceKey'
            application/protobuf:
              schema:
                type: string
                format: binary
      parameters:
      - name: lastSync
        in: query
        description: ''
        required: false
        schema:
          type: integer
          format: long
  /v1/debug/traceKey:
    post:
      summary: uploadTraceKey
      description: uploadTraceKey
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ch.ubique.notifyme.sdk.backend.model.TraceKey'
        description: N/A
components:
  schemas:
    ch.ubique.notifyme.sdk.backend.model.TraceKey:
      type: object
      required:
      - secretKey
      - startTime
      - endTime
      properties:
        secretKey:
          type: string
          format: binary
        startTime:
          type: integer
          format: long
        endTime:
          type: integer
          format: long
