openapi: 3.0.0
servers:
- url: https://app-dev-ws.notify-me.ch
  description: ''
- url: https://app-prod-ws.notify-me.ch
  description: ''
info:
  version: 1.0-MVP
  description: NotifyMe API
  title: NotifyMe API
paths:
  /v1/:
    get:
      summary: hello
      description: Hello return
      responses:
        '200':
          description: server live
          content:
            application/json:
              schema:
                type: string
  /v1/traceKeys:
    get:
      summary: getTraceKeysJson
      description: getTraceKeysJson
      responses:
        '200':
          description: protobuf/json of all keys in that interval. response header
            _x-key-bundle-tag_ contains _lastKeyBundleTag_ for next request
          headers:
            x-key-bundle-tag:
              schema:
                type: integer
                format: long
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ch.ubique.notifyme.sdk.backend.model.TraceKey'
            application/protobuf:
              schema:
                type: string
                format: binary
        '404':
          description: Invalid _lastKeyBundleTag_
      parameters:
      - name: lastKeyBundleTag
        in: query
        description: in millis since epoch. must be aligned to a full hour, and <
          now()
        example: ''
        required: false
        schema:
          type: integer
          format: long
  /v1/debug/:
    get:
      summary: hello
      description: Hello return
      responses:
        '200':
          description: server live
          content:
            application/json:
              schema:
                type: string
  /v1/debug/traceKey:
    post:
      summary: uploadTraceKey
      description: uploadTraceKey
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
      parameters:
      - name: startTime
        in: query
        description: ''
        required: true
        schema:
          type: integer
          format: long
      - name: endTime
        in: query
        description: ''
        required: true
        schema:
          type: integer
          format: long
      - name: ctx
        in: query
        description: url base64 encoded encrypted secret key
        example: ''
        required: true
        schema:
          type: string
      - name: message
        in: query
        description: ''
        required: true
        schema:
          type: string
components:
  schemas:
    ch.ubique.notifyme.sdk.backend.model.TraceKey:
      type: object
      required:
      - secretKey
      - startTime
      - endTime
      properties:
        id:
          type: integer
        startTime:
          type: integer
          format: long
        endTime:
          type: integer
          format: long
        createdAt:
          type: integer
          format: long
        message:
          type: string
